window.TEMPLATE_SHOP_ITEMS = [
  { title: "Celestial Waltz", category: "piano", difficulty: "Intermediate", pdf: "assets/shop/templates/celestial-waltz.pdf", audio: "assets/shop/templates/celestial-waltz-demo.mp3", description: "Dreamy recital-ready piano solo with optional pedal notes." },
  { title: "Autumn Lanterns", category: "strings", difficulty: "Intermediate", pdf: "assets/shop/templates/autumn-lanterns.pdf", audio: "assets/shop/templates/autumn-lanterns-demo.mp3", description: "Warm string quartet arrangement with dynamic swells." },
  { title: "Starlit Processional", category: "orchestra", difficulty: "Advanced", pdf: "assets/shop/templates/starlit-processional.pdf", audio: "assets/shop/templates/starlit-processional-demo.mp3", description: "Ceremonial processional cue for chamber orchestra." },
  { title: "Garden Hymn", category: "choir", difficulty: "Intermediate", pdf: "assets/shop/templates/garden-hymn.pdf", audio: "assets/shop/templates/garden-hymn-demo.mp3", description: "SATB choir texture with lush sustained harmony." },
  { title: "Skybridge Overture", category: "symphony", difficulty: "Advanced", pdf: "assets/shop/templates/skybridge-overture.pdf", audio: "assets/shop/templates/skybridge-overture-demo.mp3", description: "Large-ensemble fanfare-style opener." },
  { title: "Harbor Nocturne", category: "piano", difficulty: "Beginner", pdf: "assets/shop/templates/harbor-nocturne.pdf", audio: "assets/shop/templates/harbor-nocturne-demo.mp3", description: "Accessible expressive solo for student recitals." },
  { title: "Evergreen Sketch", category: "strings", difficulty: "Beginner", pdf: "assets/shop/templates/evergreen-sketch.pdf", audio: "assets/shop/templates/evergreen-sketch-demo.mp3", description: "Short lyrical miniature for young ensembles." },
  { title: "Mariner's Crest", category: "orchestra", difficulty: "Intermediate", pdf: "assets/shop/templates/mariners-crest.pdf", audio: "assets/shop/templates/mariners-crest-demo.mp3", description: "Adventure-themed orchestral concert feature." },
  { title: "Mosaic Alleluia", category: "choir", difficulty: "Advanced", pdf: "assets/shop/templates/mosaic-alleluia.pdf", audio: "assets/shop/templates/mosaic-alleluia-demo.mp3", description: "Energetic modern choir showcase." },
  { title: "Silver Pines", category: "symphony", difficulty: "Intermediate", pdf: "assets/shop/templates/silver-pines.pdf", audio: "assets/shop/templates/silver-pines-demo.mp3", description: "Pastoral symphonic suite movement." },
  { title: "Opal Tide", category: "piano", difficulty: "Intermediate", pdf: "assets/shop/templates/opal-tide.pdf", audio: "assets/shop/templates/opal-tide-demo.mp3", description: "Flowing arpeggio-based solo with cinematic color." },
  { title: "Ravenflight", category: "strings", difficulty: "Advanced", pdf: "assets/shop/templates/ravenflight.pdf", audio: "assets/shop/templates/ravenflight-demo.mp3", description: "Fast rhythmic figure writing for skilled players." },
  { title: "Summit Call", category: "orchestra", difficulty: "Intermediate", pdf: "assets/shop/templates/summit-call.pdf", audio: "assets/shop/templates/summit-call-demo.mp3", description: "Broad brass-led theme with dramatic pacing." },
  { title: "Morning Benediction", category: "choir", difficulty: "Beginner", pdf: "assets/shop/templates/morning-benediction.pdf", audio: "assets/shop/templates/morning-benediction-demo.mp3", description: "Gentle opening piece ideal for service sets." },
  { title: "Aurora Arc", category: "symphony", difficulty: "Advanced", pdf: "assets/shop/templates/aurora-arc.pdf", audio: "assets/shop/templates/aurora-arc-demo.mp3", description: "Feature-length tone poem in three sections." }
];
